### ISSUE TITLE
few puzzles 

### ISSUE THREAD

**Issue by LiuJinzhe-Keepgoing** [abdelfattah-lab/shadow_llm#6]
Very interesting job, I really want to follow, but I have a few puzzles.
1. I want to know how to download and use WikiText2 data set.

2. What is the relationship between Dejavu and llm-interpret? My understanding llm-interpret trained a predictor, and then applied this predictor under the Dejavu project to get the final sparse model reasoning result?

3. I encountered the following error when running med_genjobs.py:
```
Traceback (most recent call last):
File "/home/liujinzhe/code/activation_decoding/shadow_llm-main/llm-interpret/med_genjobs.py", line 82, in <module>
base_cmd = f'sbatch --requeue slurmrunner_medium.slurm "python emnlp_activation_predictor.py --fewshot {fews} --dataset {task}  --dataset_cname {tasks_imp_path_dict[task]} --zcp_metric {zcp_tom} --basemodel opt-13b --execmode train --emb_style {model_type} --rerun"'
KeyError: 'piqa'
```

I look forward to your reply very much. Thank you.

**Comment by akhauriyash** [comment]
1. For WikiText2, you can use lm_eval_harness (lm-eval), this is a standard procedure. In our code its automatic so you should not have to worry about it. However, in case you are interested in general, I found this good codebase: https://github.com/andy-yang-1/DoubleSparse/blob/main/evaluation/perplexity_eval.py#L20 --> This code shows how to use wikitext. 

2. We implement ShadowLLM and reimplement DejaVu within the llm-interpret framework. That is where we generate our accuracy results. As for the performance results, we use the Dejavu framework, and modify it to emulate the predictor. We trained AND applied the predictor under llm-interpret. In our current implementation, our predictor training +accuracy evaluation and performance evaluation are separate. We are working on a new codebase which implements both accuracy and performance evaluation together, but its still in progress.

3. As you can see in the code, we initialize the dictionary as shown below:
tasks = ["wikitext"]
tasks_imp_path = ["wikitext"]
tasks_imp_path_dict = dict(zip(tasks, tasks_imp_path))

This initialization only works for wikitext, if you want piqa, you need to take 


tasks = ["piqa", "copa", "openbookqa", "winogrande", "rte", "hellaswag", "arc_easy"]
tasks_imp_path = ["piqa", "copa", "openbookqa", "winogrande", "rte", "hellaswag", "arc_easy"]
tasks_imp_path_dict = dict(zip(tasks, tasks_imp_path))

This will map piqa correctly.

Hope this helps!

**Comment by LiuJinzhe-Keepgoing** [comment]
This really helped me a lot. 
Thank you so much, my bro！！！
